# Generated by Django 5.2 on 2025-05-05 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientNeeds",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.IntegerField()),
                ("needed", models.CharField(max_length=255)),
                ("important", models.IntegerField()),
                ("urgency", models.IntegerField()),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="RequirementProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("adscription", models.CharField(max_length=255)),
                ("charge", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("business_knowledge", models.IntegerField()),
                ("market_knowledge", models.IntegerField()),
                ("time_availability", models.IntegerField()),
                ("comunication_skills", models.IntegerField()),
                ("system_interaction", models.IntegerField()),
                ("autority_range", models.IntegerField()),
                ("informatic_knowledge", models.IntegerField()),
                ("project_compromise", models.IntegerField()),
                ("puntuation", models.FloatField()),
                ("result", models.CharField(max_length=255)),
                ("ranking", models.IntegerField()),
                ("auxiliary", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("aproved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequirementClient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.IntegerField()),
                ("solicited_requirement", models.CharField(max_length=255)),
                ("solicited_at", models.DateTimeField()),
                ("is_modified", models.BooleanField()),
                ("is_tracked", models.BooleanField()),
                ("decision", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
                (
                    "client_needs_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requirements.clientneeds",
                    ),
                ),
                (
                    "requirement_provider_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requirements.requirementprovider",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clientneeds",
            name="requirement_provider_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="requirements.requirementprovider",
            ),
        ),
    ]
